### ISSUE TITLE
App crashes if user has no profile photo

### ISSUE THREAD

**Issue by jsonfry** [DCRichards/stravadora#1]
Love the app! But if you use a token for a user with no profile photo, as you start the app it crashes.

**Comment by DCRichards** [comment]
Thanks @jsonfry! It seems that Strava returns `/avatar/athlete/medium.png` as the image URL if there isn't a profile image set (apparently I'm not the only one [who thinks that's strange](https://groups.google.com/forum/#!topic/strava-api/sn0BoB4FDfY)). I'll make sure I handle that case, I should probably make sure there's some kind of placeholder/default image too.
